language: objective-c
matrix:
  include:
    - osx_image: xcode8.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
branches:
  only:
    - master
script:
  - xcodebuild test -workspace FluxCapacitor.xcworkspace -scheme FluxCapacitorTests -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
notifications:
  email:
    on_success: never
    on_failure: always
